### ISSUE TITLE
Importing problem

### ISSUE THREAD

**Issue by SonicSpeed139920** [Gl2imm/RBX_Toolbox#7]
Hello.Whenever I want to export my character or a Roblox Studio model, it gives me this error

importing character:Python: Traceback (most recent call last):
  File "C:\Users\Home\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\RBX_Toolbox\__init__.py", line 1163, in execute
    rbx_imp_acc = bpy.ops.import_scene.obj(filepath=rbx_obj_file)
UnboundLocalError: local variable 'rbx_obj_file' referenced before assignment

imporing items:Python: Traceback (most recent call last):
  File "C:\Users\Home\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\RBX_Toolbox\__init__.py", line 3379, in draw
    box.label(text = 'Type: ' + rbx_asset_type_name)
TypeError: can only concatenate str (not "NoneType") to str

we need help.
we need a new update for 4.0 Version

**Comment by Gl2imm** [comment]
Thx for the feedback.. Fixed issue in version 4.5 Toolbox.
